name: Deploy Docker Image

on:
  workflow_run:
    workflows:
      - Build Docker Image
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to EC2 via SSM
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Pull & restart on EC2 via SSM
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        id: ssm
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          working-directory: /home/ubuntu/cogo-server
          command: |
            cd /home/ubuntu/cogo-server
            echo "Deploy 시작"
            docker pull coffeego/cogo-server:latest
            docker rm -f cogo-server || true
            docker run -d \
              --name cogo-server \
              --env-file /home/ubuntu/cogo-server/.env \
              -p 80:8080 \
              coffeego/cogo-server:latest
          comment: "Deploy latest cogo-server"
